/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.ClienteDAO;
import Control.ClientesObject;
import View.popups.confirmExit;
import Control.TaskCategoriaDAO;
import Control.TasksModelDAO;
import Model.Clientes;
import Model.FrameTask;
import Model.TaskCategoria;
import Model.TasksModel;
import View.popups.CriarCategoria;
import View.popups.CriarTask;
import View.popups.EditarTask;
import View.popups.confirmRemove;
import View.popups.confirmRemoveTask;
import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.Rectangle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.TableColumn;
import javax.swing.border.Border;
/**
 *
 * @author Zaymã Kinsiona
 */
public class UserTasks extends javax.swing.JFrame {
    
    public static String categoria_selecionada = "";
    public static int id_task_selecionada = -1;
    
    
    public UserTasks(){
        initComponents();
        
        
        try {
            ClientesObject usuario = Clientes.initilizateData();
            username.setText(usuario.nome);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UserTasks.class.getName()).log(Level.SEVERE, null, ex);
        }
        ScrollTasks.setLayout(new GridLayout(50,1,-1,7));
        ScrollTasks.repaint();
        
        TaskCategoria.loadRequest();
        TasksModel.loadTaskRequest();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoText = new javax.swing.JLabel();
        select_types = new javax.swing.JComboBox<>();
        ScrollPane = new javax.swing.JScrollPane();
        ScrollTasks = new javax.swing.JPanel();
        add_task = new javax.swing.JButton();
        add_category = new javax.swing.JButton();
        TaskTitle = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        bemvindo = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        info = new javax.swing.JPanel();
        TaskNameInfo = new javax.swing.JLabel();
        descInfo = new javax.swing.JScrollPane();
        textInfo = new javax.swing.JTextArea();
        validadeInfo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        isDonePainel = new javax.swing.JPanel();
        editTask = new javax.swing.JButton();
        removeCategoria = new javax.swing.JButton();
        removeTask = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(642, 570));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        infoText.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        infoText.setForeground(new java.awt.Color(102, 102, 255));
        infoText.setText("Info");

        select_types.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        select_types.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma Categoria" }));
        select_types.setToolTipText("");
        select_types.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 255)));
        select_types.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        select_types.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                select_typesItemStateChanged(evt);
            }
        });

        ScrollPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 255)));
        ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        ScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        ScrollPane.setAutoscrolls(true);
        ScrollPane.setMaximumSize(new java.awt.Dimension(100, 32767));
        ScrollPane.setPreferredSize(new java.awt.Dimension(12, 2));
        ScrollPane.setWheelScrollingEnabled(false);

        ScrollTasks.setAutoscrolls(true);

        javax.swing.GroupLayout ScrollTasksLayout = new javax.swing.GroupLayout(ScrollTasks);
        ScrollTasks.setLayout(ScrollTasksLayout);
        ScrollTasksLayout.setHorizontalGroup(
            ScrollTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );
        ScrollTasksLayout.setVerticalGroup(
            ScrollTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );

        ScrollPane.setViewportView(ScrollTasks);

        add_task.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Assets/plusIcon.png"))); // NOI18N
        add_task.setBorder(null);
        add_task.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_task.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_taskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_taskMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                add_taskMousePressed(evt);
            }
        });
        add_task.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_taskActionPerformed(evt);
            }
        });

        add_category.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Assets/plusIcon2.jpg"))); // NOI18N
        add_category.setBorder(null);
        add_category.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_categoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_categoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                add_categoryMousePressed(evt);
            }
        });
        add_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_categoryActionPerformed(evt);
            }
        });

        TaskTitle.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        TaskTitle.setForeground(new java.awt.Color(102, 51, 255));
        TaskTitle.setText("Selecione a categoria");

        title1.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        title1.setForeground(new java.awt.Color(51, 51, 255));
        title1.setText("Tasks");

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));

        username.setBackground(new java.awt.Color(0, 0, 0));
        username.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 21)); // NOI18N
        username.setForeground(new java.awt.Color(204, 204, 204));
        username.setText("Zaymã");

        bemvindo.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 21)); // NOI18N
        bemvindo.setForeground(new java.awt.Color(255, 255, 255));
        bemvindo.setText("Olá");

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Assets/logOutIcon.png"))); // NOI18N
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sair");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(bemvindo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bemvindo)
                        .addComponent(username)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        info.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), null, null, new java.awt.Color(102, 102, 255)));

        TaskNameInfo.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 21)); // NOI18N

        textInfo.setEditable(false);
        textInfo.setColumns(20);
        textInfo.setRows(5);
        textInfo.setText("\n");
        textInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 255)));
        textInfo.setFocusable(false);
        descInfo.setViewportView(textInfo);

        validadeInfo.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 15)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Concluir");

        isDonePainel.setBackground(new java.awt.Color(192, 191, 191));
        isDonePainel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isDonePainelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isDonePainelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isDonePainelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout isDonePainelLayout = new javax.swing.GroupLayout(isDonePainel);
        isDonePainel.setLayout(isDonePainelLayout);
        isDonePainelLayout.setHorizontalGroup(
            isDonePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        isDonePainelLayout.setVerticalGroup(
            isDonePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        editTask.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        editTask.setForeground(new java.awt.Color(51, 51, 255));
        editTask.setText("Editar");
        editTask.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 255)));
        editTask.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoLayout.createSequentialGroup()
                        .addComponent(TaskNameInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addGroup(infoLayout.createSequentialGroup()
                        .addComponent(isDonePainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editTask, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(validadeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
                    .addContainerGap(41, Short.MAX_VALUE)
                    .addComponent(descInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(TaskNameInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(validadeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(isDonePainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editTask, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
            .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
                    .addContainerGap(128, Short.MAX_VALUE)
                    .addComponent(descInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(72, Short.MAX_VALUE)))
        );

        removeCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Assets/excluir.png"))); // NOI18N
        removeCategoria.setBorder(null);
        removeCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCategoriaActionPerformed(evt);
            }
        });

        removeTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Assets/remove.png"))); // NOI18N
        removeTask.setBorder(null);
        removeTask.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(TaskTitle)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(removeTask, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(add_task, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(6, 6, 6)))
                    .addComponent(title1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(select_types, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(add_category, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoText)
                        .addGap(16, 16, 16))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_category, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(infoText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(title1)
                            .addComponent(select_types, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(removeTask, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TaskTitle)
                            .addComponent(add_task))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_taskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_taskActionPerformed

        if(TaskTitle.getText() == "Selecione a categoria"){
            JOptionPane.showMessageDialog(null, "Selecione uma categoria antes de adicionar uma task.");
        }else{
            CriarTask callTask = new CriarTask();
            callTask.setLocation(getWidth() / 3,getHeight()/ 4);
            callTask.setVisible(true);
        } 
        
    }//GEN-LAST:event_add_taskActionPerformed

    private void add_taskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_taskMouseEntered

        add_task.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new Color(102,102,255), null, null, new java.awt.Color(51, 51, 255)));
    }//GEN-LAST:event_add_taskMouseEntered

    private void add_taskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_taskMouseExited
        add_task.setBorder(null);
        add_task.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_add_taskMouseExited

    private void add_taskMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_taskMousePressed
        add_task.setBackground(new Color(51,51,255));
     
    }//GEN-LAST:event_add_taskMousePressed

    private void add_categoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_categoryMouseEntered
        add_category.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new Color(102,102,255), null, null, new java.awt.Color(51, 51, 255)));
    }//GEN-LAST:event_add_categoryMouseEntered

    private void add_categoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_categoryMouseExited
        add_category.setBorder(null);
        add_category.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_add_categoryMouseExited

    private void add_categoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_categoryMousePressed
        add_category.setBackground(new Color(51,51,255));
    }//GEN-LAST:event_add_categoryMousePressed

    private void add_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_categoryActionPerformed

        CriarCategoria openJFrame = new CriarCategoria();
        openJFrame.setLocation(getWidth() / 3,getHeight()/ 4);
        openJFrame.setVisible(true);
        
        
    }//GEN-LAST:event_add_categoryActionPerformed

    private void select_typesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_select_typesItemStateChanged

        if(evt.getStateChange() == 1){
            ScrollTasks.removeAll();
            categoria_selecionada = evt.getItem().toString();
            TaskCategoriaDAO get = new TaskCategoriaDAO();
            TaskCategoria obj = get.getCateg(evt.getItemSelectable().getSelectedObjects()[0].toString());
            TaskTitle.setText(obj.nomeCategoria.getText());
            TaskTitle.setForeground(obj.corCategoria);

            TasksModel.loadSelectRequest(obj.nomeCategoria.getText());
            repaint();
        }
      
    }//GEN-LAST:event_select_typesItemStateChanged

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        confirmExit exitFrame = new confirmExit();
        exitFrame.setLocation(getWidth() / 3,getHeight()/ 3);
        exitFrame.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        repaint();
    }//GEN-LAST:event_formMouseMoved

    private void isDonePainelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isDonePainelMouseEntered
        isDonePainel.setBorder(javax.swing.BorderFactory.createLineBorder(Color.black, 1));
    }//GEN-LAST:event_isDonePainelMouseEntered

    private void isDonePainelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isDonePainelMouseExited
        isDonePainel.setBorder(null);
    }//GEN-LAST:event_isDonePainelMouseExited

    private void isDonePainelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isDonePainelMouseClicked
        if(id_task_selecionada != -1){
            TasksModel.taskCompleteRequest(id_task_selecionada);
        } 
        
    }//GEN-LAST:event_isDonePainelMouseClicked

    private void editTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTaskActionPerformed
        if(id_task_selecionada != -1){
            EditarTask edit = new EditarTask();
            edit.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma task");
        }
        
    }//GEN-LAST:event_editTaskActionPerformed

    private void removeCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCategoriaActionPerformed
        if(TaskTitle.getText() != "Selecione a categoria"){
          
            confirmRemove remove = new confirmRemove();
            remove.setLocation(getWidth() / 3,getHeight()/ 4);
            remove.jLabel1.setText("Deseja mesmo remover " + TaskTitle.getText() + "?");
            remove.setVisible(true);
        }
        
    }//GEN-LAST:event_removeCategoriaActionPerformed

    private void removeTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTaskActionPerformed
        if(id_task_selecionada != -1) {
            confirmRemoveTask taskRemove = new confirmRemoveTask();
            taskRemove.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma task");
        }
        
    }//GEN-LAST:event_removeTaskActionPerformed
    public static void updateList(JLabel nome, Color cor){
        select_types.addItem(nome.getText());

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserTasks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    public static javax.swing.JPanel ScrollTasks;
    public static javax.swing.JLabel TaskNameInfo;
    public static javax.swing.JLabel TaskTitle;
    private javax.swing.JButton add_category;
    private javax.swing.JButton add_task;
    private javax.swing.JLabel bemvindo;
    private javax.swing.JScrollPane descInfo;
    private javax.swing.JButton editTask;
    public static javax.swing.JPanel info;
    private javax.swing.JLabel infoText;
    public static javax.swing.JPanel isDonePainel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton removeCategoria;
    private javax.swing.JButton removeTask;
    public static javax.swing.JComboBox<String> select_types;
    public static javax.swing.JTextArea textInfo;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel username;
    public static javax.swing.JLabel validadeInfo;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getSelect_types() {
        return select_types;
    }

    public void setSelect_types(JComboBox<String> select_types) {
        this.select_types = select_types;
    }
}
